#!/usr/bin/env python
# Copyright (c) 2015, NORDUnet A/S

import sys
from irrexplorer import utils, sqldb, report


def main():

    if len(sys.argv) == 1:
        print "No argument given"
        sys.exit(1)

    dsn = "dbname=irrexplorer"
    db = sqldb.IRRSQLDatabase(dsn)

    for arg in sys.argv[1:]:
        try:
            so = utils.classifySearchString(arg)

            if type(so) is utils.Prefix:
                result = report.prefix_report(db, so.value)
                # prefix report already prints some stuff (consider changing that)

            if type(so) is utils.ASNumber:
                result = report.as_report(db, so.value)
                for prefix, sources in result['prefixes'].items():
                    print prefix, sources.keys()
                print
                for macro, sources in result['macros'].items():
                    print macro, sources.keys()

            if type(so) is utils.ASMacro:
                #res = db.query_as_macro(so.value)
                result = report.as_macro_report(db, so.value)
                for e in result['expanded']:
                    print e
                print
                for macro, sources in result['macros'].items():
                    print macro, ' '.join(sources.keys())

        except ValueError as e:
            print str(e)


if __name__ == '__main__':
    main()
