#!/bin/sh


# Create database

echo "Please input sudo password to create irrexplorer database (or do it manually)"
sudo su - postgres -c "createdb irrexplorer"


# Fetch irr databases

./fetch irr.yml

# Create file with SQL insert statements:

zcat *.db*.gz | ./create_inserts > irr.sql

# BGP route table dump

wget http://lg01.infra.ring.nlnog.net/table.txt
./create_bgp_insert < table.txt > bgp.sql

# And the ripe managed space

cat ../data/ripe-managed-space.txt |./create_ripe_managed  > ripe_managed.sql


### Loading database

# Load data

psql irrexplorer -f ripe_managed.sql
psql irrexplorer -f irr.sql
psql irrexplorer -f bgp.sql


