#!/bin/sh


# Create database

echo "Please input sudo password to create irrexplorer database (or do it manually)"
sudo su - postgres -c "createdb irrexplorer"
psql irrexplorer -f ../data/schema.sql


# Fetch irr databases

./fetch irr.yml

# Create file with SQL insert statements:

zcat *.db*.gz | ./create_irr_inserts > irr.sql

# Create serial

./create_serials > serials.sql

# BGP route table dump

wget http://lg01.infra.ring.nlnog.net/table.txt
./create_bgp_insert < table.txt > bgp.sql

# And the ripe managed space

cat ../data/ripe-managed-space.txt |./create_ripe_managed  > ripe_managed.sql


### Loading database

# Load data

psql irrexplorer -f ripe_managed.sql
psql irrexplorer -f irr.sql
psql irrexplorer -f serials.sql
psql irrexplorer -f bgp.sql

