#!/usr/bin/env python

import fileinput
import sys


def main():

    import irrparser

    sources = {}
    for line in open('sources.map').readlines():
        source, id_ = line.strip().split(',')
        sources[source] = id_

    object_data = []
    for line in fileinput.input():
        if not line == '\n':
            object_data.append(line)
        else:
            obj, values = irrparser.irrParser(object_data)
            object_data = []

            if obj == irrparser.AS_SET:
                members = '{' + ','.join(values[1]) + '}'

                source = sources.get(values[2])
                if source is None:
                    print >> sys.stderr, 'No source for object: ', values[0], members
                    continue

                fields = (values[0], members, source )
                print '|'.join(fields)


if __name__ == '__main__':
    sys.path.insert(0, '../irrexplorer') # hack on :-)
    main()
