#!/usr/bin/env python

import fileinput
import sys
import ipaddr


def main():

    import irrparser

    sources = {}
    for line in open('sources.map').readlines():
        source, id_ = line.strip().split(',')
        sources[source] = id_

    object_data = []
    for line in fileinput.input():
        if not line == '\n':
            object_data.append(line)
        else:
            obj, values = irrparser.irrParser(object_data)
            object_data = []

            if obj == irrparser.ROUTE:
                try:
                    ipaddr.IPNetwork(values[0], strict=True)
                except ValueError as e:
                    if 'does not appear to be' in str(e):
                        pass # usually leading zero in v4 octets, we can handle those
                    else:
                        print >> sys.stderr, str(e), 'source: ', values[2]
                        continue

                source = sources.get(values[2])
                if source is None:
                    print >> sys.stderr, 'No source for object: ', values[0], values[1]
                    continue

                fields = ( values[0], str(values[1]), source )
                print '|'.join(fields)


if __name__ == '__main__':
    sys.path.insert(0, '../irrexplorer') # hack on :-)
    main()
