#!/usr/bin/env python

import sys

INSERT = "SELECT create_route ('%s', %s, 'bgp');"

PG_MAX_INTEGER = 2147483647

def main():

    i = 1
    print 'BEGIN;'
    for line in sys.stdin:

        route, origin = line.strip().split(' ',1)
        print INSERT % (route, origin)
        i += 1
        if i % 5000 == 0:
            print 'COMMIT;'
            print 'BEGIN;'

    print 'COMMIT;'


if __name__ == '__main__':
    main()

