#!/usr/bin/env python

import sys
import ipaddr


def main():

    import irrparser

    sources = {}
    for line in open('sources.map').readlines():
        source, id_ = line.strip().split(',')
        sources[source] = id_

    parser = irrparser.irrParser(sys.stdin)

    for obj, values in parser:

        if obj == irrparser.ROUTE:
            try:
                ipaddr.IPNetwork(values[0], strict=True)
            except ValueError as e:
                if 'does not appear to be' in str(e):
                    pass # usually leading zero in v4 octets, we can handle those
                else:
                    print >> sys.stderr, str(e), 'source: ', values[2]
                    continue

            source = sources.get(values[2])
            if source is None:
                print >> sys.stderr, 'No source for object: ', values[0], values[1]
                continue

            fields = ( values[0], str(values[1]), source )
            print '|'.join(fields)


if __name__ == '__main__':
    sys.path.insert(0, '../irrexplorer') # hack on :-)
    main()

