#!/usr/bin/env python

import sys
import sources

bgp_id = sources.getSourceMap()['bgp']


def main():

    for line in sys.stdin:

        route, origin = line.strip().split(' ',1)
        print '%s|%s|%s' % (route, origin, bgp_id)


if __name__ == '__main__':
    main()

